### ISSUE TITLE
not working on latest arch

### ISSUE THREAD

**Issue by rkunschke** [Zren/plasma-hud#14]
I am running arch on latest plasma desktop and the appmenu just works fine. I installed the HUD via AUR and maped the dbus call to an shortcut as you desciped in the readme. I watched the terminal output of your script and nothing is happening. I called the function via qdbusviewer and it returned nothing: Received reply from :1.905 (no arguments)

**Comment by Zren** [comment]
Which app(s) are you testing with?

Hmm. So you have the appmenu widget (or button in the titlebar) exporting the menu, so that's not the problem. You've restarted (or ran the `plasma-hud` script in the terminal) so the script is running.

It's either find this `xprop` missing and (or empty as it is in firefox):

```
_GTK_MENUBAR_OBJECT_PATH(UTF8_STRING) = "/org/appmenu/gtk/window/3"
```

Or it's not finding the KDE AppMenu `xprop` code:

```
_KDE_NET_WM_APPMENU_OBJECT_PATH(STRING) = "/com/canonical/menu/400002C"
_KDE_NET_WM_APPMENU_SERVICE_NAME(STRING) = ":1.59"
```

It's still working in Manjaro (which is a ~week behind Arch).

**Comment by rkunschke** [comment]
I tested with dolphin, Konsole, Chromium etc... 
plasma-hud was running in my terminal so i would see all outputs of it.
What does these paths mean?

**Comment by Zren** [comment]
That window metadata (which can been seen with the `xprop` command) is the dbus paths used to fetch the menus.

`LOGLEVEL=DEBUG plasma-hud` will show that info.

**Comment by rkunschke** [comment]
I have fixed the problem with adding 
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
to the /etc/profile
there was a warning in the console about a missing locale setting.
